application: wallet-thing
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: /static/favicon.ico
  upload: /static/favicon.ico
  
- url: /static/bootstrap/css
  static_dir: wallet/static/bootstrap/css
  
- url: /static/datatables/css
  static_dir: wallet/static/datatables/css
  
- url: .*
  script: main.app