"""empty message

Revision ID: 19edb0619a95
Revises: 2cc5117acec
Create Date: 2015-01-11 22:55:01.375452

"""

# revision identifiers, used by Alembic.
revision = '19edb0619a95'
down_revision = '2cc5117acec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_order',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('clientTypeID', sa.Integer(), nullable=True),
    sa.Column('stationID', sa.Integer(), nullable=True),
    sa.Column('volEntered', sa.Integer(), nullable=True),
    sa.Column('volRemaining', sa.Integer(), nullable=True),
    sa.Column('minVolume', sa.Integer(), nullable=True),
    sa.Column('orderState', sa.Integer(), nullable=True),
    sa.Column('typeID', sa.Integer(), nullable=True),
    sa.Column('range', sa.Integer(), nullable=True),
    sa.Column('accountKey', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('escrow', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bid', sa.Boolean(), nullable=True),
    sa.Column('issued', sa.DateTime(), nullable=True),
    sa.Column('charID', sa.Integer(), nullable=True),
    sa.Column('corporationID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charID'], ['api_character.characterID'], ),
    sa.ForeignKeyConstraint(['corporationID'], ['api_corporation.corporationID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_order')
    ### end Alembic commands ###
