"""empty message

Revision ID: 1cf99137d64
Revises: 59d40cbbeede
Create Date: 2015-07-11 15:53:12.850256

"""

# revision identifiers, used by Alembic.
revision = '1cf99137d64'
down_revision = '59d40cbbeede'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crest_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('adjustedPrice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('averagePrice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('href', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crest_item')
    ### end Alembic commands ###
