"""empty message

Revision ID: 28d74cae9b18
Revises: None
Create Date: 2015-01-09 19:39:59.747048

"""

# revision identifiers, used by Alembic.
revision = '28d74cae9b18'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_api',
    sa.Column('keyID', sa.Integer(), nullable=False),
    sa.Column('vCode', sa.String(length=80), nullable=True),
    sa.Column('accessMask', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('Account', 'Character', 'Corporation', name='api_apitypes'), nullable=True),
    sa.PrimaryKeyConstraint('keyID')
    )
    op.create_table('api_character',
    sa.Column('characterID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('homeStationID', sa.Integer(), nullable=True),
    sa.Column('DoB', sa.DateTime(), nullable=True),
    sa.Column('race', sa.String(length=8), nullable=True),
    sa.Column('bloodLine', sa.String(length=20), nullable=True),
    sa.Column('ancestry', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('corporationName', sa.String(length=80), nullable=True),
    sa.Column('corporationID', sa.Integer(), nullable=True),
    sa.Column('allianceName', sa.String(length=80), nullable=True),
    sa.Column('allianceID', sa.Integer(), nullable=True),
    sa.Column('factionName', sa.String(length=80), nullable=True),
    sa.Column('factionID', sa.Integer(), nullable=True),
    sa.Column('cloneTypeID', sa.Integer(), nullable=True),
    sa.Column('cloneName', sa.String(length=20), nullable=True),
    sa.Column('cloneSkillPoints', sa.Integer(), nullable=True),
    sa.Column('freeSkillPoints', sa.Integer(), nullable=True),
    sa.Column('freeRespecs', sa.Integer(), nullable=True),
    sa.Column('cloneJumpDate', sa.DateTime(), nullable=True),
    sa.Column('lastRespecDate', sa.DateTime(), nullable=True),
    sa.Column('lastTimedRespec', sa.DateTime(), nullable=True),
    sa.Column('remoteStationDate', sa.DateTime(), nullable=True),
    sa.Column('jumpActivation', sa.DateTime(), nullable=True),
    sa.Column('jumpFatigue', sa.DateTime(), nullable=True),
    sa.Column('jumpLastUpdate', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('characterID')
    )
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('_password', sa.LargeBinary(length=120), nullable=True),
    sa.Column('_salt', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_apicharacter',
    sa.Column('characterID', sa.Integer(), nullable=True),
    sa.Column('keyID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterID'], ['api_character.characterID'], ),
    sa.ForeignKeyConstraint(['keyID'], ['api_api.keyID'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_apicharacter')
    op.drop_table('users_user')
    op.drop_table('api_character')
    op.drop_table('api_api')
    ### end Alembic commands ###
