"""empty message

Revision ID: 2cc5117acec
Revises: 50c6927cfcd5
Create Date: 2015-01-10 23:53:32.221908

"""

# revision identifiers, used by Alembic.
revision = '2cc5117acec'
down_revision = '50c6927cfcd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_transaction',
    sa.Column('transactionDateTime', sa.DateTime(), nullable=True),
    sa.Column('transactionID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('typeName', sa.String(length=80), nullable=True),
    sa.Column('typeID', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('clientID', sa.Integer(), nullable=True),
    sa.Column('clientName', sa.String(length=80), nullable=True),
    sa.Column('stationID', sa.Integer(), nullable=True),
    sa.Column('stationName', sa.String(length=80), nullable=True),
    sa.Column('transactionType', sa.Enum('buy', 'sell', name='api_transactiontypes'), nullable=True),
    sa.Column('transactionFor', sa.Enum('personal', 'corporation', name='api_transactiontypes'), nullable=True),
    sa.Column('journalTransactionID', sa.BigInteger(), nullable=True),
    sa.Column('clientTypeID', sa.Integer(), nullable=True),
    sa.Column('characterID', sa.Integer(), nullable=True),
    sa.Column('corporationID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characterID'], ['api_character.characterID'], ),
    sa.ForeignKeyConstraint(['corporationID'], ['api_corporation.corporationID'], ),
    sa.PrimaryKeyConstraint('transactionID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_transaction')
    ### end Alembic commands ###
