"""empty message

Revision ID: 33c93a3476fe
Revises: 2a4c81b07b7a
Create Date: 2015-09-06 21:58:21.049408

"""

# revision identifiers, used by Alembic.
revision = '33c93a3476fe'
down_revision = '2a4c81b07b7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crest_item', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('crest_item', sa.Column('volume', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crest_item', 'volume')
    op.drop_column('crest_item', 'published')
    ### end Alembic commands ###
