"""empty message

Revision ID: 3423b06e0df9
Revises: 31178742e3b5
Create Date: 2015-07-11 21:59:58.339360

"""

# revision identifiers, used by Alembic.
revision = '3423b06e0df9'
down_revision = '31178742e3b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crest_marketstat',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('current_buy', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_buy_1day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_buy_7day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_sell', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_sell_1day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_sell_7day', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('type_id', 'station_id')
    )
    op.create_table('crest_markethistory',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('average_volume', sa.Integer(), nullable=True),
    sa.Column('average_orders', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('type_id', 'region_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crest_markethistory')
    op.drop_table('crest_marketstat')
    ### end Alembic commands ###
