"""empty message

Revision ID: 43a2904f24c0
Revises: None
Create Date: 2015-01-08 21:37:27.819919

"""

# revision identifiers, used by Alembic.
revision = '43a2904f24c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('corporationID', sa.Integer(), nullable=True),
    sa.Column('corporationName', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('_password', sa.LargeBinary(length=120), nullable=True),
    sa.Column('_salt', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Corporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('ticker', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('Api',
    sa.Column('keyID', sa.Integer(), nullable=False),
    sa.Column('vCode', sa.String(length=80), nullable=True),
    sa.Column('accessMask', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('Account', 'Character', 'Corporation', name='api_types'), nullable=True),
    sa.PrimaryKeyConstraint('keyID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Api')
    op.drop_table('Corporation')
    op.drop_table('users_user')
    op.drop_table('Character')
    ### end Alembic commands ###
