"""empty message

Revision ID: 4662196d152
Revises: 19edb0619a95
Create Date: 2015-06-30 23:06:55.989244

"""

# revision identifiers, used by Alembic.
revision = '4662196d152'
down_revision = '19edb0619a95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_user',
    sa.Column('character_owner_hash', sa.String(length=32), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('character_name', sa.String(length=50), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('refresh_token', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('character_owner_hash')
    )
    op.drop_table('users_user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('_password', sa.BLOB(), nullable=True),
    sa.Column('_salt', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sso_user')
    ### end Alembic commands ###
