"""empty message

Revision ID: 49aba4738913
Revises: 4662196d152
Create Date: 2015-06-30 23:17:14.278552

"""

# revision identifiers, used by Alembic.
revision = '49aba4738913'
down_revision = '4662196d152'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
