"""empty message

Revision ID: 56b111f9c48b
Revises: 49aba4738913
Create Date: 2015-06-30 23:17:22.710967

"""

# revision identifiers, used by Alembic.
revision = '56b111f9c48b'
down_revision = '49aba4738913'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
