"""empty message

Revision ID: 5848d14a7db
Revises: None
Create Date: 2014-07-25 00:11:42.731000

"""

# revision identifiers, used by Alembic.
revision = '5848d14a7db'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hash', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Corporation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('ticker', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('Character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('corporationID', sa.Integer(), nullable=True),
    sa.Column('corporationName', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vcode', sa.String(length=80), nullable=True),
    sa.Column('access_mask', sa.Integer(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['Character.id'], ),
    sa.ForeignKeyConstraint(['corporation_id'], ['Corporation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Api')
    op.drop_table('Character')
    op.drop_table('Corporation')
    op.drop_table('User')
    ### end Alembic commands ###
