"""empty message

Revision ID: 59d40cbbeede
Revises: 56b111f9c48b
Create Date: 2015-07-02 21:53:16.269777

"""

# revision identifiers, used by Alembic.
revision = '59d40cbbeede'
down_revision = '56b111f9c48b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sso_user') as batch_op:
        batch_op.drop_column('token')
        batch_op.drop_column('expires')
        batch_op.drop_column('refresh_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sso_user', sa.Column('refresh_token', sa.VARCHAR(length=50), nullable=True))
    op.add_column('sso_user', sa.Column('expires', sa.INTEGER(), nullable=True))
    op.add_column('sso_user', sa.Column('token', sa.VARCHAR(length=50), nullable=True))
    ### end Alembic commands ###
