"""empty message

Revision ID: ddabf99c0b1
Revises: None
Create Date: 2014-07-23 21:46:26.365000

"""

# revision identifiers, used by Alembic.
revision = 'ddabf99c0b1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
